require 'rake'
require 'rspec/core/rake_task'

task :default => :test

desc 'Run specs'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Dir.glob('spec/**/*_spec.rb')
  t.rspec_opts = '--format documentation'
  t.rspec_opts << ' --color'
end

task :test => [
  :spec,
]